"""BC TSR document indexing helpers."""

from __future__ import annotations

from .cache import (
    TsrCacheError,
    TsrCacheFailure,
    TsrDownloadedPdf,
    TsrFetchResult,
    TsrInventoryDocument,
    fetch_tsr_pdfs,
    load_tsr_document_inventory,
)
from .crawl import (
    DEFAULT_TSR_LANDING_URL,
    DEFAULT_TSR_PUBLISH_ROOT_URL,
    DEFAULT_TSR_TSA_ROOT_URL,
    TsaRegistryRecord,
    TsrCatalogError,
    TsrCycleRecord,
    TsrDocumentRecord,
    TsrIndexResult,
    TsrLandingResource,
    TsrWrittenIndex,
    index_tsr_tsa_surfaces,
    write_tsr_index,
)
from .extract import (
    TsrCandidateFact,
    TsrExtractError,
    TsrExtractResult,
    TsrExtractionFailure,
    extract_tsr_candidate_facts,
)
from .overlay import (
    TsrOverlayCanonicalSummary,
    TsrOverlayError,
    TsrOverlayInitResult,
    TsrOverlayRecord,
    TsrOverlayReport,
    TsrOverlayTsaRecord,
    build_tsr_overlay_report,
    init_tsr_overlay,
    load_tsr_overlay,
)

__all__ = [
    "DEFAULT_TSR_LANDING_URL",
    "DEFAULT_TSR_PUBLISH_ROOT_URL",
    "DEFAULT_TSR_TSA_ROOT_URL",
    "TsrCandidateFact",
    "TsaRegistryRecord",
    "TsrCacheError",
    "TsrCacheFailure",
    "TsrCatalogError",
    "TsrCycleRecord",
    "TsrDownloadedPdf",
    "TsrDocumentRecord",
    "TsrExtractError",
    "TsrExtractResult",
    "TsrExtractionFailure",
    "TsrFetchResult",
    "TsrInventoryDocument",
    "TsrIndexResult",
    "TsrLandingResource",
    "TsrOverlayCanonicalSummary",
    "TsrOverlayError",
    "TsrOverlayInitResult",
    "TsrOverlayRecord",
    "TsrOverlayReport",
    "TsrOverlayTsaRecord",
    "TsrWrittenIndex",
    "build_tsr_overlay_report",
    "extract_tsr_candidate_facts",
    "fetch_tsr_pdfs",
    "index_tsr_tsa_surfaces",
    "init_tsr_overlay",
    "load_tsr_document_inventory",
    "load_tsr_overlay",
    "write_tsr_index",
]
